[package]
name = "combootcha"
version = "0.1.0"
authors = ["Sean Fisk <sean@seanfisk.com>"]
edition = "2021"

[dependencies]
nix = { version = "0.27", default-features = false, features = ["user"] }
clap = "2.34"
clap-logging = { git = "https://github.com/seanfisk/clap-logging.git", tag = "v0.2.0" }
anyhow = "1"
log = { version = "0.4", features = ["std"] }
users = "0.11"
chrono = "0.4"
atty = "0.2"
serde_json = "1"
plist = "1"
subprocess = "0.2"
reqwest = { version = "0.11", features = ["blocking"] }
tempfile = "3"
#directories = "2.0.2"
#Inflector = "0.11.4"

# The Colored crate is also a choice for colorization in Rust: https://github.com/mackwic/colored#features
#
# Colored implements the Standard for ANSI Colors in Terminals, which is something we want to implement. However, it
# implements the auto-colorization behavior by checking whether *stdout is a TTY*. However, we print colors to both
# stdout (via clap) and stderr (via our logging subsystem). The TTY check is really something that needs to be
# implemented *per stream*. clap does this properly, and we want to do it properly for our logging subsystem, too.
# Therefore, we've implemented the Standard for ANSI Colors in Terminals manually in our own code and configuration
# auto-colorization per standard stream. Although it's possible to ignore this feature in Colored (but not disable it),
# ansi_term does not even attempt to implement the Standard for ANSI Colors in Terminals, so there is no conflict in the
# feature set it is providing.
ansi_term = "0.11.0" # Synchronized with clap to prevent an extra dependency

[build-dependencies]
anyhow = "1"
cc = "1"
bindgen = "0.68"