[package]
name = "personal-computing-setup"
version = "0.1.0"
authors = ["Sean Fisk <sean@seanfisk.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.18.0"
clap = "2.33"
anyhow = "1.0"
#log = {version = "0.4.8", features = ["std"]}
#ansi_term = "0.11.0"
#directories = "2.0.2"
#Inflector = "0.11.4"

