# Personal only

# brew 'aria2'
# brew 'dfc' # An improved version of df with colors.
# brew 'gibo'
# brew 'graphviz'
# brew 'grc'
# brew 'pstree'
# brew 'qpdf'
# brew 'thefuck'

# Fun commands
# brew 'figlet'
# brew 'sl'
# brew 'toilet'

#cask 'adobe-reader' # Failing right now
#cask 'quicksilver'
cask 'firefox'
cask 'spotify'
cask 'google-earth-pro'
cask 'slack' # Blue Medora Bros, Grand Rapids

# Useful for sites that don't work well in Firefox or Safari, like midnrreservations.com and many others
#
# Broadcom installs a company-managed Chrome, so keep the cask personal only.
cask 'google-chrome'

# From https://www.reddit.com/r/emulation/comments/8w1lqd/comment/e1ryp97/
#
#     RetroArch has now gained a Metal renderer! Targeting modern macOS at first. XMB/MaterialUI works, menu shader pipelines work, Slang shaders work thanks to SPIRV-Cross, fonts work, etc!
#
#     Previously, RetroArch for OSX/macOS only had an OpenGL video driver. Since Apple will be deprecating OpenGL support in the near future, this Metal video driver essentially future proofs RetroArch for mac!﻿
#
# So, let's go with Metal instead of OpenGL.
cask 'retroarch-metal'

# A game to play with blue-iq-krew
# https://www.bzflag.org/getting-started/
cask 'bzflag'

# On initial computer setup, App Store will prompt for an Apple ID which is stored in my password manager. Therefore, to make this easier, all apps installed with mas should be listed in the Brewfile *after* the password manager.

mas 'Microsoft To Do', id: 1274495053
