# Personal only

# brew 'aria2'
# brew 'dfc' # An improved version of df with colors.
# brew 'gibo'
# brew 'graphviz'
# brew 'grc'
# brew 'pstree'
# brew 'qpdf'
# brew 'thefuck'

# Fun commands
# brew 'figlet'
# brew 'sl'
# brew 'toilet'

#cask 'adobe-reader' # Failing right now
#cask 'gfxcardstatus'
#cask 'quicksilver'
#cask 'retroarch-metal' # 'retroarch' cask is also available, but I think the Metal renderer is supposed to be better
cask 'firefox'
cask 'spotify'
cask 'lastpass'
