# -*- mode: ruby -*-

# Bundler for Homebrew
# https://github.com/Homebrew/homebrew-bundle

brew 'git'
brew 'emacs-mac', args: ['--with-spacemacs-icon']

# Install X11 software
# Note: XQuartz is installed to /Applications/Utilities/XQuartz.app
cask 'xquartz'
# These formulae require XQuartz to be installed first
brew 'xclip'
cask 'inkscape'

mas 'LastPass Password Manager', id: 926036361
